CREATE TABLE IF NOT EXISTS PORTFOLIO.RAW.EQUITY_DAILY (
  SYMBOL STRING NOT NULL,
  DATE DATE NOT NULL,
  OPEN NUMBER(18,6),
  HIGH NUMBER(18,6),
  LOW  NUMBER(18,6),
  CLOSE NUMBER(18,6),
  VOLUME NUMBER(38,0),
  SOURCE STRING,
  _ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_equity_daily PRIMARY KEY (SYMBOL, DATE)
)
CLUSTER BY (symbol, date);

CREATE TABLE IF NOT EXISTS PORTFOLIO.RAW.FX_DAILY (
  PAIR STRING NOT NULL,  
  DATE DATE NOT NULL,
  RATE NUMBER(18,8),
  SOURCE STRING,
  _ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_fx_daily PRIMARY KEY (PAIR, DATE)
)
CLUSTER BY (pair, date);

CREATE TABLE IF NOT EXISTS PORTFOLIO.RAW.LOAD_METADATA (
  source STRING NOT NULL,
  last_loaded_date DATE,
  _updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_load_metadata PRIMARY KEY (source)
);

CREATE TABLE IF NOT EXISTS PORTFOLIO.RAW.PORTFOLIO_POSITIONS (
  PORTFOLIO_ID STRING NOT NULL,
  SYMBOL STRING NOT NULL,
  QUANTITY NUMBER(18,6) NOT NULL,
  _ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_positions PRIMARY KEY (portfolio_id, symbol)
);

CREATE TABLE IF NOT EXISTS PORTFOLIO.ANALYTICS.PIPELINE_MONITORING (
  run_id STRING NOT NULL,
  run_date DATE NOT NULL,
  task_name STRING NOT NULL,
  status STRING NOT NULL,
  record_count NUMBER,
  error_message STRING,
  _logged_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Transactions log
CREATE TABLE IF NOT EXISTS PORTFOLIO.RAW.PORTFOLIO_TRANSACTIONS (
  transaction_id STRING NOT NULL,
  portfolio_id   STRING NOT NULL,
  symbol         STRING NOT NULL,
  quantity_delta NUMBER(18,6) NOT NULL,
  transaction_date DATE NOT NULL,
  transaction_type STRING NOT NULL,  --  BUY, SELL, INIT etc
  _ingested_at   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_transactions PRIMARY KEY (transaction_id)
);

-- Daily positions snapshot (incrementally maintained)
CREATE TABLE IF NOT EXISTS PORTFOLIO.ANALYTICS.PORTFOLIO_POSITIONS_DAILY (
  portfolio_id STRING NOT NULL,
  symbol       STRING NOT NULL,
  date         DATE NOT NULL,
  quantity     NUMBER(18,6) NOT NULL,
  _created_at  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_positions_daily PRIMARY KEY (portfolio_id, symbol, date)
);
CREATE OR REPLACE TABLE PORTFOLIO.RAW.FACT_BENCHMARK (
    DATE DATE NOT NULL,
    SYMBOL STRING NOT NULL,
    CLOSE NUMBER(18,6),
    PRIMARY KEY (DATE, SYMBOL)
);

CREATE OR REPLACE TABLE PORTFOLIO.ANALYTICS.FACT_PORTFOLIO_ADV_METRICS (
    DATE DATE NOT NULL,
    PORTFOLIO_ID STRING NOT NULL,
    SHARPE_RATIO FLOAT,
    SORTINO_RATIO FLOAT,
    MAX_DRAWDOWN FLOAT,
    BETA FLOAT,
    ALPHA FLOAT,
    PRIMARY KEY (DATE, PORTFOLIO_ID)
);
