CREATE TABLE IF NOT EXISTS PORTFOLIO.RAW.EQUITY_DAILY (
  SYMBOL STRING NOT NULL,
  DATE DATE NOT NULL,
  OPEN NUMBER(18,6),
  HIGH NUMBER(18,6),
  LOW  NUMBER(18,6),
  CLOSE NUMBER(18,6),
  VOLUME NUMBER(38,0),
  SOURCE STRING,
  _ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_equity_daily PRIMARY KEY (SYMBOL, DATE)
);

CREATE TABLE IF NOT EXISTS PORTFOLIO.RAW.FX_DAILY (
  PAIR STRING NOT NULL,   -- e.g., USD/EUR, GBP/EUR
  DATE DATE NOT NULL,
  RATE NUMBER(18,8),
  SOURCE STRING,
  _ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_fx_daily PRIMARY KEY (PAIR, DATE)
);

CREATE TABLE IF NOT EXISTS PORTFOLIO.RAW.LOAD_METADATA (
  source STRING NOT NULL,
  last_loaded_date DATE,
  _updated_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_load_metadata PRIMARY KEY (source)
);

CREATE TABLE IF NOT EXISTS PORTFOLIO.RAW.PORTFOLIO_POSITIONS (
  PORTFOLIO_ID STRING NOT NULL,
  SYMBOL STRING NOT NULL,
  QUANTITY NUMBER(18,6) NOT NULL,
  _ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT pk_positions PRIMARY KEY (portfolio_id, symbol)
);


